language: node_js
node_js:
  - 0.6
before_script:
  - ./utils/travis.sh

script: npm test

notifications:
  irc: "irc.freenode.org#iks"
  email: 
    recipients:
      - viejs@googlegroups.com
      - sebastian.germesin@dfki.de
    on_success: change
    on_failure: change
